### ISSUE TITLE
Can't locate info on privileged containers in documentation

### ISSUE THREAD

**Issue by jdandrea** [01org/ciao#1636]
Placeholder issue for updating the docs: There's now support for privileged containers, affording a kind of (unofficial?) bare metal support:

```
requirements:
    vcpus: 2
    mem_mb: 512
    privileged: true
```
