### ISSUE TITLE
Path and Readonly status of volumes missing from START payload

### ISSUE THREAD

**Issue by markdryan** [01org/ciao#607]
When we mount a ceph volume into an instance we have the option to specify whether that container should be readonly or not.    Both QEMU and docker allow us to specify that a drive or volume should be read only so there's no technical reason not to support this.

Docker also allows us to specify where a volume should be mounted.  Currently, volumes are mounted inside the container at /volumes/<UUID>, but it would probably be easier for end users if they had more control over this.

I don't think it's possible to control the device name a ceph volume gets inside a qemu instance but we can check.

Anyway, our new payload might look something like this.

```
start:
  ... 
  storage:
        id: 67d86208-000-4465-9018-fe14087d415f
        mode: ro
        boot: false
        mount: /media/ceph/images
```
